Feature/validaciones
xariasavila/simple-monkey-android pull request #5
Opened 2020-04-23 07:14 UTC by xariasavila

Validaciones en login
Validaciones en registro usuario
Se agregó la APP BAR
Se quitó  APP BAR de splashscreen
Modificacion formato de fecha yyyy-mm-dd a dd-mm-yyyy
Se agregó link en terminos y condiciones

2020-04-25 16:30 UTC, borisbelmar requested changes
Xavi, te dejé unos cambios en el código. Lo otro... Cuando probé las interfaces de usuarios, el login se pierde con la barra de arriba, creo que tanto en el login como en el registro puede llegar a ser innecesaria. Derrepente la mataría ahí y la agregaría en los interiores.

2020-04-25 16:30 UTC, borisbelmar commented on app/src/main/java/com/example/simplemonkey/AccountLogin.java
> +    String email,pass;
Mantengamos la convención de tipo de dato antes del nombre, es decir, email y pass a strEmail y strPassword. Ojo con las variables, no usemos abreviaturas pass -> password

2020-04-25 16:30 UTC, borisbelmar commented on app/src/main/java/com/example/simplemonkey/AccountRegister.java
> +    String firstname,lastname,email,gender,birth, pass,repass;
Mismo tema de arriba, ojo con las convenciones de espacios

Tipo variable1, variable2, variable3

2020-04-25 16:30 UTC, borisbelmar commented on app/src/main/java/com/example/simplemonkey/AccountRegister.java
> +
Ojo con usar muchos espacios, el código se alarga por gusto D: Tenemos que separar las validaciones en clases aparte porque estamos repitiendo mucho código por gusto (Principio DRY - Dont repeat yourself)

2020-04-25 16:30 UTC, borisbelmar commented on app/src/main/java/com/example/simplemonkey/AccountRegister.java
> +
Lo mismo con los espacios

2020-04-25 16:30 UTC, borisbelmar commented on app/src/main/res/layout/activity_account_register.xml
> +                android:onClick="loguearCheckbox"/>
A que está llamando este onClick? D:

2020-04-25 16:30 UTC, borisbelmar commented on app/src/main/res/layout/activity_main.xml
> +
Muchos espacios D:

2020-04-25 16:30 UTC, borisbelmar commented on app/src/main/res/values/styles.xml
> +    <style name="AppTheme" parent="Theme.AppCompat.Light.DarkActionBar">
Deberíamos ver como aplicarlo en ciertas pantallas

2020-04-25 21:09 UTC, xariasavila commented on app/src/main/java/com/example/simplemonkey/AccountLogin.java
> +    String email,pass;
corregido

2020-04-25 21:19 UTC, xariasavila commented on app/src/main/java/com/example/simplemonkey/AccountRegister.java
> +    String firstname,lastname,email,gender,birth, pass,repass;
ok

2020-04-25 21:20 UTC, xariasavila commented on app/src/main/res/layout/activity_account_register.xml
> +                android:onClick="loguearCheckbox"/>
ok

2020-04-25 21:21 UTC, xariasavila commented on app/src/main/res/layout/activity_main.xml
> +
Esta dejala asi no más estoy probando el tema del floating buttom wea

2020-04-25 21:22 UTC, xariasavila commented on app/src/main/res/values/styles.xml
> +    <style name="AppTheme" parent="Theme.AppCompat.Light.DarkActionBar">
Corregido

2020-04-29 04:57 UTC, borisbelmar commented on app/src/main/res/layout/activity_main.xml
> +
Esta se va a pisar con el PR que voy a pasar del dashboard

2020-04-29 04:59 UTC, borisbelmar commented
@xariasavila pasé varios cambios a tu PR. Las validaciones las encapsulé en una clase que maneja todas las validaciones. Tengo que documentarlas, pero usarla es súper fácil. Además en el AccountRegister, comenté la línea 56. Pégale un ojo, porque me estaba rompiendo la app.

`tvTerms.setMovementMethod(LinkMovementMethod.getInstance());`

Saludines

2020-04-29 18:49 UTC, borisbelmar approved these changes

2020-04-29 18:49 UTC, merged